# Utilisez l'image officielle de Node.js comme base
FROM node:14-alpine

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers de votre application dans le conteneur
COPY . .

# Installez les dépendances
#RUN npm install

# Construisez l'application
#RUN npm run build

# Définissez le port d'écoute de l'application
EXPOSE 3500

# Démarrez l'application lorsque le conteneur est lancé
CMD ["npm", "start"]